name: project2501a
favicon: null
layout_spectrum: 0.0886383184697479
typography_spectrum: 0.3711000808980316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8447037148289382
  lightness: 0.9717847872525454
  saturation: 0.2678375910036266
  rhythmicContrast: 0.3779271552339196
purpose: []
